# Generated by Django 4.2.7 on 2023-11-27 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_goods_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='name',
            field=models.CharField(max_length=25, verbose_name='Название товара'),
        ),
    ]
