# Generated by Django 4.2.7 on 2023-12-03 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_goods_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parametr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True, verbose_name='Параметр товару')),
            ],
            options={
                'verbose_name': 'Parametr',
                'verbose_name_plural': 'Parametrs',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='goods',
            name='parametr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parametr', to='catalog.parametr'),
        ),
    ]
