# Generated by Django 4.2.7 on 2023-12-20 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_parametr_goods_parametr'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='id')),
                ('url', models.URLField(blank=True, verbose_name='Url')),
                ('width', models.IntegerField(blank=True, verbose_name='width')),
                ('height', models.IntegerField(blank=True, verbose_name='height')),
            ],
            options={
                'verbose_name': 'Excel Category',
                'verbose_name_plural': 'Excel Categories',
                'ordering': ['name'],
            },
        ),
    ]
