# Generated by Django 4.2.7 on 2024-01-19 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_goods_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название товара'),
        ),
    ]
